### ISSUE TITLE
Autostrafer

### ISSUE THREAD

**Issue by synvy** [DucaRii/csgo_modest#10]
```
void autostrafe()
{
	if (!config::get<bool>(ctx::cfg.movement_autostrafe))
		return;

	if (!ctx::client.local || !ctx::client.local->is_alive())
		return;

	/// No need to bhop there
	const auto move_type = ctx::client.local->get_move_type();
	if (move_type == MOVETYPE_LADDER ||
		move_type == MOVETYPE_NOCLIP ||
		move_type == MOVETYPE_OBSERVER)
		return;

	/// Is player underwater?
	if (ctx::client.local->get_water_level() >= 2)
		return;

	if (!ctx::client.local->get_flags().has_flag(FL_ONGROUND))
	{
		if (ctx::client.cmd->mousedx < 0)
			ctx::client.cmd->sidemove = -450.0f;
		else if (ctx::client.cmd->mousedx > 0)
			ctx::client.cmd->sidemove = 450.0f;
	}
}
```

Simple autostrafe :P
Would be nice to see it added in real quick.

**Comment by alpine971** [comment]
not good autostrafe

**Comment by synvy** [comment]
> 
> 
> not good autostrafe

Yea, but it's simple, quick, and it works.  This is supposed to be used as a base, correct?  If people want a better strafer, they should add one themselves.  Just thought it would be nice to have that in since bhop is already in there.

**Comment by outlassn** [comment]
`	void autostrafe()
	{
		if ( !config::get<bool>( ctx::cfg.movement_autostrafe ) )
			return;

		/// Is player underwater / onground? Autostrafe won't work in these conditions
		if ( ctx::client.local->get_flags().has_flag( FL_ONGROUND ) )
			return;

		/// Allow movement if movement keys are pressed
		if ( ctx::client.cmd->buttons.has_flag( IN_MOVERIGHT ) || ctx::client.cmd->buttons.has_flag( IN_MOVELEFT ) 
		  || ctx::client.cmd->buttons.has_flag( IN_FORWARD )   || ctx::client.cmd->buttons.has_flag( IN_BACK ) )
			return;

		if ( ctx::client.local->get_velocity().length_2d() < 50.f )
		{
			/// This gets called if the player is standing still and holds the space bar
			set_autostrafe_movement( calculate_best_rotation( 320.f ) );
		}
		else if ( ctx::client.cmd->mousedx > 1 || ctx::client.cmd->mousedx < -1 )
		{
			/// This gets called if the player is manually strafing with their mouse
			ctx::client.cmd->sidemove = ctx::client.cmd->mousedx < 0.f ? -450.f : 450.f;
		}
		else
		{
			/// This gets called if the player is not strafing with their mouse, but already has some velocity
			set_autostrafe_movement( calculate_best_rotation( ctx::client.local->get_velocity().length_2d() ) );
		}
	}

	float calculate_best_rotation( float ideal_velocity )
	{
		float ideal_rotation = std::min( math::rad2deg( std::asinf( 30.f / ideal_velocity ) ) * 0.5f, 45.f );
		float turn_direction_modifier = ctx::client.cmd->command_number % 2 ? 1.f : -1.f;

		ctx::client.cmd->forwardmove = 0.f;
		ctx::client.cmd->sidemove = 450.f;

		float best_rotation = ( ideal_rotation - 90.f ) * turn_direction_modifier;
		
		return best_rotation;
	}

	void set_autostrafe_movement( float current_rotation )
	{
		float sin_rotation = sin( math::deg2rad( current_rotation ) );
		float cos_rotation = cos( math::deg2rad( current_rotation ) );

		float new_forwardmove = ( sin_rotation * ctx::client.cmd->forwardmove ) + ( cos_rotation * ctx::client.cmd->sidemove );
		float new_sidemove = ( cos_rotation * ctx::client.cmd->forwardmove ) + ( sin_rotation * ctx::client.cmd->sidemove );

		ctx::client.cmd->forwardmove = new_forwardmove;
		ctx::client.cmd->sidemove = new_sidemove;
	}`

much better, enjoy pasta

**Comment by DucaRii** [comment]
I don't feel like a base needs a lot ( if any ) features at all.
